"""AuthToken

Revision ID: 1d62efd58836
Revises: fa04395ee397
Create Date: 2023-06-16 22:03:01.450671

"""
from alembic import op
import sqlalchemy as sa
from src.auth.models import TokenChoicesTypes, AuthToken


# revision identifiers, used by Alembic.
revision = '1d62efd58836'
down_revision = 'fa04395ee397'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('token_type', TokenChoicesTypes(AuthToken.TOKEN_TYPES), nullable=False),
    sa.Column('token_owner', sa.String(length=150), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expired', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_tokens')
    # ### end Alembic commands ###
