"""Added tasks models

Revision ID: 9749b5c21194
Revises: 9213d30ede4f
Create Date: 2023-06-29 16:17:19.038910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9749b5c21194'
down_revision = '9213d30ede4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('task_text', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('expired', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
