"""empty message

Revision ID: 9213d30ede4f
Revises: 786fbcf73dbf
Create Date: 2023-06-21 00:06:32.607575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9213d30ede4f'
down_revision = '786fbcf73dbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
